### PR TITLE
made changes

### PR DESCRIPTION
**Pull request by Leader254**

### CODE REVIEW

**Comment by Leader254** [comment]
added a new pattern for the gitignore

**Comment by SamuelOkoth** [comment]
on bransh working clean

**Comment by SamuelOkoth** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form Input Types and Attributes</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <form>
        <h1 style="text-align: center;">Form Input Types and Attributes</h1>
        
        <label for="text-input">Enter your name:</label>
        <input type="text" id="text-input" placeholder="Enter your name
here" pattern="[a-zA-Z]+" minlength="2" maxlength="10" required><br>

        
        <label for="email-input">Email:</label>
        <input type="email" id="email-input" placeholder="Enter your email"
***@***.***+\.[a-zA-Z]{2,}" required><br>

        
        <label for="password-input">Password Input:</label>
        <input type="password" id="password-input" minlength="8" required><
br>

        
        <label for="number-input">Year of study</label>
        <input type="number" id="number-input" min="1" max="4" required><br>

        
        <label for="date-input">Graduation date</label>
        <input type="date" id="date-input" required><br>

        
        <label for="time-input">Time Input:</label>
        <input type="time" id="time-input" required><br>

        
        <label for="url-input">Url to Your Github</label>
        <input type="url" id="url-input" required><br>

        <label for="url-input">Url to Your Linkedin</label>
        <input type="url" id="url-input" required><br>

        <label for="file-input">Upload Your Pic</label>
        <input type="file" id="file-input" multiple><br>

        <h4>Choose your Course</h4>
        <input type="radio" id="course1" name="course" value="computer">
        <label for="course1">Computer Science</label><br>
        <input type="radio" id="course2" name="course" value="swe">
        <label for="course2">Software Engineering</label><br>
        <input type="radio" id="course3" name="course" value="infotech">
        <label for="course3">Information Technology</label><br>
        <input type="radio" id="course4" name="course" value="csys">
        <label for="course4">Computer Sysytems</label><br><br>

        
        <h4>Languages</h4>
        <label for="checkbox-input">Javascript</label>
        <input type="checkbox" id="checkbox-input" checked><br>

        <label for="checkbox-input">Python</label>
        <input type="checkbox" id="checkbox-input"><br>

        <label for="checkbox-input">C#</label>
        <input type="checkbox" id="checkbox-input"><br>

        
        <label for="gsearch">Search Others:</label>
        <input type="search" id="gsearch" name="gsearch">
        <input type="submit" value="Search"><br><br>

        <label for="select-input">Experience Level</label>
        <select id="select-input" required>
            <option value="">Choose 1</option>
            <option value="option1">Beginner</option>
            <option value="option2">Intermediate</option>
            <option value="option3">Advanced</option>
            <option value="option4">Proffesional</option>
        </select><br><br>

        
        <label for="vol">Working Hours (between 0 and 24):</label>
        <input type="range" id="vol" name="vol" min="0" max="24"><br><br>

        
        <h4>Frameworks and Libraries</h4>
        <label for="radio-input1">React Js</label>
        <input type="radio" id="radio-input1" name="radio-group" value=
"radio1" required checked><br>

        <label for="radio-input2">Django</label>
        <input type="radio" id="radio-input2" name="radio-group" value=
"radio2" required><br>

        <label for="radio-input3">Node Js</label>
        <input type="radio" id="radio-input3" name="radio-group" value=
"radio3" required><br>

        <label for="radio-input4">Angular</label>
        <input type="radio" id="radio-input4" name="radio-group" value=
"radio4" required><br>

        <label for="textarea-input">Leave your comment here :</label>
        <textarea id="textarea-input" rows="4" cols="50" minlength="10"
required></textarea><br><br>

        
        <input type="button" onclick="alert('Hello World!')" value="Submit">
        <input type="reset">
    </form>
</body>
</html>

**Comment by SamuelOkoth** [comment]
/* general styling */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: Arial, sans-serif;
    font-size: 16px;
    line-height: 1.5;
    background-color: #f7f7f7;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
}

form {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 10px;
}

h1 {
    margin-bottom: 20px;
}

h4 {
    margin-bottom: 10px;
}

label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

input,
select,
textarea {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    width: 100%;
    margin-bottom: 15px;
    font-size: 16px;
}

input[type="radio"],
input[type="checkbox"] {
    margin-top: 5px;
    margin-right: 5px;
}

input[type="submit"],
input[type="reset"],
button {
    background-color: #4CAF50;
    border: none;
    color: #fff;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    margin-top: 10px;
}

input[type="submit"]:hover,
input[type="reset"]:hover,
button:hover {
    background-color: #3e8e41;
}

/* responsive design */
@media only screen and (max-width: 600px) {

    .container {
        max-width: 100%;
        padding: 10px;
    }

    input,
    select,
    textarea {
        font-size: 14px;
    }

    input[type="submit"],
    input[type="reset"],
    button {
        font-size: 14px;
        padding: 8px 16px;
    }

}

**Pull request merged**
